#index:
#    path: /
#    controller: App\Controller\DefaultController::index

main_page:
     path: /
     controller: App\Controller\MainController::index

admin_page:
      path: /admin
      controller: App\Controller\MainController::admin

register:
      path: /register
      controller: App\Controller\Auth\RegisterController::registerAction